# Generated by Django 5.2.4 on 2025-07-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_classroom_code_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='code',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
